---
- name: test ping with ansible
  hosts: windows
  tasks:
      - name : add hosts
        add_host:
         hostname: 192.168.0.105
         ansible_user: Interview
         ansible_password: admatic123
         ansible_port: 5986
         ansible_connection: winrm
         # The following is necessary for Python 2.7.9+ when using default WinRM self-signed       certificates:
         ansible_winrm_server_cert_validation: ignore

      - name: Ping
        win_ping:

